apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-user-rs
  namespace: secret-dungeon
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: server-user-rs
          image: gmae199boy/secret-dungeon-user-rs:0.0.2
          ports:
            - containerPort: 3000
              name: user-port
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secret-dungeon-db
                  key: DB_URL
